@port=3001
@host=http://localhost:{{port}}/api

POST  {{host}}/user
Content-Type: application/json

{
     "firstName":"mousa",
     "lastName":"hammad",
    "email":"mm@mgddfd9.com",
    "city":"jerusalem",
    "password":"123456",
    "gender":"זכר",
    "dateBirthDay":"01/01/1994",
    "admin":true,
    "dogTrainer":false,
    "dogWalker":false,
    "image":"https://images.app.goo.gl/C9RQ7Jg6HVJtN48m6",
    "phone":"052789456"
    
}
###

POST {{host}}/auth
Content-Type: application/json

{
    "email":"mm@mgddfd9.com",
    "password":"123456"
}

###

GET {{host}}/user/me 
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMwOTkyZTQxZWQ4NGMzMjQ0MDliMzIiLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6dHJ1ZSwiZG9nV2Fsa2VyIjpmYWxzZSwiaWF0IjoxNjQ3MzUyMTMwfQ.mXOch9lJ-HmUdU444niuvSdv7pAkax4kZ8Xyjv89NR0
    

###
POST  {{host}}/cardTrain
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMwOWI4MWJhMjUzOTJjNjc1MzVlYjAiLCJhZG1pbiI6dHJ1ZSwiZG9nVHJhaW5lciI6ZmFsc2UsImRvZ1dhbGtlciI6ZmFsc2UsImlhdCI6MTY0NzM1MjcxNn0.3M7ALTIFYm_ndKpAohjbNq0wYDOusAcsMLKkkfIQVA0
Content-Type: application/json

{
    "experience":5,
    "trainWay":true,
    "cost":"100-200",
    "timeTrain":1.5

}


